Repository lwe/page_title_helper, pull requests merged in 2024-11, with the labels that each got.

#197 [FEATURE] Add support for Rails 8.0
  .github/workflows/ci.yml
  CHANGELOG.md
  gemfiles/Gemfile.rails-8.0
  page_title_helper.gemspec
Labels: hacktoberfest

#202 [DOCS] Autoformat the changelog
  CHANGELOG.md
Labels: cleanup

#203 [TASK] Update the development dependencies
  page_title_helper.gemspec
Labels: dependencies
